config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/weather', to: 'weather#weather'
  post '/current_weather', to: 'weather#current_weather'

  # Defines the root path route ("/")
  root "weather#weather"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
require 'weather_app_client'

class WeatherController < ApplicationController

  def weather; end

  def current_weather
    case params[:commit]
    when 'Current Weather'
      is_cached = Rails.cache.exist?("#{address.zip}-current_weather")
      @weather = fetch_data(:current_weather)
      render turbo_stream: turbo_stream.update('current_weather', WeatherCardComponent.new(weather: @weather, address: address, cached: is_cached))
    when 'Forecast'
      is_cached = Rails.cache.exist?("#{address.zip}-forecast")
      @weathers = fetch_data(:forecast).dig('list')
      render turbo_stream: turbo_stream.update('forecast_weather', WeatherCardComponent.with_collection(@weathers, address: address, title: 'Forecast', cached: is_cached))
    else
      @weather = weather_app_client.send(:current_weather)
    end
  end

  private

  def fetch_data(method)
    if Rails.cache.exist?("#{address.zip}-#{method}}")
      Rails.cache.read("#{address.zip}-#{method}}")
    else
      response = weather_app_client.send(method)
      Rails.cache.write("#{address.zip}-#{method}", response, expires_in: 30.minutes)
      response
    end
  end

  def address
    @address = OpenStruct.new(city: address_params[:city],
                              state: address_params[:state],
                              zip: address_params[:zip],
                              country: address_params[:country])
  end

  def address_params
    params.permit(:authenticity_token, :city, :state, :zip, :country_code, :commit)
  end

  def weather_app_client
    @weather_app_client ||= ::WeatherAppClient.new(city: address.city,
                                                   state: address.state,
                                                   zip: address.zip,
                                                   country: address.country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/weather/weather.html.erb
<div class="flex flex-col">
  <div class="mx-auto">
    <h1 class="text-8xl mb-12">WEATHER NOW</h1>
  </div>
  <div class="mx-auto">
    <%= form_tag(current_weather_path) do %>
      <div class="mb-4">
        <%= label_tag :city, nil, class: 'block text-gray-600 font-semibold' %>
        <%= text_field_tag :city, nil, class: 'form-input', required: true %>
      </div>

      <div class="mb-4">
        <%= label_tag :state, nil, class: 'block text-gray-600 font-semibold' %>
        <%= text_field_tag :state, nil, class: 'form-input',  required: true %>
      </div>

      <div class="mb-4">
        <%= label_tag :zip, nil, class: 'block text-gray-600 font-semibold' %>
        <%= text_field_tag :zip, nil, class: 'form-input',  required: true %>
      </div>

      <div class="mb-4">
        <%= label_tag :country_code, nil, class: 'block text-gray-600 font-semibold' %>
        <%= text_field_tag :country_code, nil, class: 'form-input',  required: true %>
      </div>

      <div class="mt-6">
        <%= submit_tag "Current Weather", class: 'bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700' %>
        <%= submit_tag "Forecast", class: 'bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-300' %>
      </div>
    <% end %>
  </div>
</div>
<div class="flex flex-row">
  <div class="mt-12 w-1/2">
    <%= turbo_frame_tag :current_weather %>
  </div>
  <div class="mt-12 w-1/2">
    <%= turbo_frame_tag :forecast_weather %>
  </div>
</div>